version: '3'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - beetime

volumes:
  pgdata:

networks:
  beetime:
    driver: bridge