version: '3'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${KEYCLOAK_DATABASE},${BACKEND_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - beetime

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      KC_DB: ${DATABASE_KIND}
      KC_DB_URL: ${DATABASE_URL}/${KEYCLOAK_DATABASE}
      DB_DATABASE: ${KEYCLOAK_DATABASE}
      KC_DB_USERNAME: ${DATABASE_USER}
      KC_DB_PASSWORD: ${DATABASE_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_TRANSACTION_XA_ENABLED: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - beetime

volumes:
  pgdata:

networks:
  beetime:
    driver: bridge